name: CMake Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Conf and B
      run: |
        cmake -S . -B build
        cmake --build build

    - name: Run
      run: ./build/singleton_app

    - name: Run tests
      run: ./build/singl_test
